# Generated by Django 2.1.2 on 2019-02-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foi_requests', '0011_add_can_publish_field_to_foi_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicbody',
            name='level',
            field=models.CharField(choices=[('Local', 'Municipal'), ('State', 'Estadual'), ('Federal', 'Federal')], default='Local', max_length=10),
        ),
        migrations.AlterField(
            model_name='foirequest',
            name='can_publish',
            field=models.BooleanField(default=True),
        ),
    ]
