# Generated by Django 2.2.28 on 2024-11-20 13:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foi_requests", "0013_auto_20190814_1521"),
    ]

    operations = [
        migrations.AddField(
            model_name="foirequest",
            name="esic_protocol_password",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
