# Generated by Django 5.2.14 on 2026-05-20 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foi_requests", "0014_foirequest_esic_protocol_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="moderation_status",
            field=models.BooleanField(
                choices=[(None, "Pending"), (True, "Approved"), (False, "Rejected")],
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="message",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("sender__isnull", False),
                    ("receiver__isnull", False),
                    _connector="OR",
                ),
                name="message_must_have_sender_or_receiver",
            ),
        ),
    ]
