language: python
python: 3.6
addons:
  postgresql: "9.5"

install: pip install tox -rrequirements.txt
before_script:
  - psql -c 'CREATE DATABASE lainonima;' -U postgres
  - cp .env.example .env
script:
  - tox
  - python manage.py migrate
  - make load_fixtures
