#!/usr/bin/env bash
# One-command development bootstrap, invoked by the devbox.json scripts
# (`devbox run dev|setup|test`). It is safe to run repeatedly.

set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."

# Devbox's PostgreSQL plugin exports PGDATA and PGHOST. The fallbacks also make
# the script usable from a `devbox shell` where those variables were unset.
: "${PGDATA:=$PWD/.devbox/virtenv/postgresql/data}"
: "${PGHOST:=$(dirname "$PGDATA")}"
export PGDATA PGHOST

APP_DB_USER=queremossaber
APP_DB_NAME=queremossaber_dev

# Initialize a checkout-local cluster on first run.
if [ ! -s "$PGDATA/PG_VERSION" ]; then
  if [ -d "$PGDATA" ] && [ -n "$(ls -A "$PGDATA" 2>/dev/null)" ]; then
    echo "devbox-bootstrap: $PGDATA exists but is not a valid Postgres cluster" >&2
    echo "devbox-bootstrap: remove the interrupted cluster and retry: rm -rf \"$PGDATA\"" >&2
    exit 1
  fi

  echo "devbox-bootstrap: initializing Postgres cluster in $PGDATA"
  mkdir -p "$PGDATA"
  initdb \
    --username="$APP_DB_USER" \
    --auth=trust \
    --encoding=UTF8 \
    "$PGDATA" >/dev/null
fi

# Use a Unix socket only, avoiding conflicts with a system Postgres or another
# checkout. The bootstrap owns this server; stop it with `devbox run db:stop`.
if ! pg_ctl -D "$PGDATA" status >/dev/null 2>&1; then
  mkdir -p "$PGHOST"
  if ! pg_ctl -D "$PGDATA" \
    -l "$PGHOST/postgres.log" \
    -o "-k $PGHOST -c listen_addresses=''" \
    start >/dev/null; then
    echo "devbox-bootstrap: Postgres failed to start; see $PGHOST/postgres.log" >&2
    exit 1
  fi
fi

for _ in $(seq 1 40); do
  pg_isready -q -h "$PGHOST" -U "$APP_DB_USER" -d postgres && break
  sleep 0.25
done
if ! pg_isready -q -h "$PGHOST" -U "$APP_DB_USER" -d postgres; then
  echo "devbox-bootstrap: Postgres did not start on socket directory $PGHOST" >&2
  echo "devbox-bootstrap: see $PGHOST/postgres.log" >&2
  exit 1
fi

# initdb creates the application role as a superuser, which lets Django create
# its temporary test database. The fallback supports clusters initialized by
# the Devbox service plugin before this script was run.
if psql -U "$APP_DB_USER" -d postgres -tAc "SELECT 1" >/dev/null 2>&1; then
  SUPERUSER="$APP_DB_USER"
else
  SUPERUSER="$(id -un)"
  psql -U "$SUPERUSER" -d postgres -tAc \
    "SELECT 1 FROM pg_roles WHERE rolname='$APP_DB_USER'" | grep -q 1 ||
    psql -U "$SUPERUSER" -d postgres -c \
      "CREATE ROLE $APP_DB_USER LOGIN SUPERUSER" >/dev/null
fi
psql -U "$SUPERUSER" -d postgres -tAc \
  "SELECT 1 FROM pg_database WHERE datname='$APP_DB_NAME'" | grep -q 1 ||
  createdb -U "$SUPERUSER" -O "$APP_DB_USER" "$APP_DB_NAME"

# Preserve an existing environment. Otherwise create the complete minimum
# local configuration required by web/settings.py.
if [ -f .env ] && ! grep -Fq "host=$PGHOST" .env; then
  echo "devbox-bootstrap: NOTE: the existing .env does not use Devbox Postgres" >&2
  echo "devbox-bootstrap: migrations will use the DATABASE_URL already in .env" >&2
  echo "devbox-bootstrap: to switch, move .env aside and run this command again" >&2
fi
if [ ! -f .env ]; then
  echo "devbox-bootstrap: writing a local-development .env"
  cat >.env <<EOF
# Generated by devbox/bootstrap.sh for local development only. Delete this
# file to regenerate it; .env.example documents the optional settings.
ENV=dev
DEBUG=True
SECRET_KEY=devbox-local-development-only-secret-key
DATABASE_URL=postgresql://$APP_DB_USER@/$APP_DB_NAME?host=$PGHOST
ENABLE_S3=False
SESSION_COOKIE_SECURE=False
CSRF_COOKIE_SECURE=False
EOF
fi

# Keep dependencies current with the lockfile, install the git hook on the
# first run, then prepare the database and generated stylesheet.
if [ ! -d .venv ]; then
  make install
else
  uv sync --all-groups
fi
uv run python manage.py migrate
[ -f web/static/web/styles/main.css ] || make sass

echo
echo "Queremos Saber is ready."
echo "  Postgres: unix socket $PGHOST (database $APP_DB_NAME; stop with 'devbox run db:stop')"
echo "  Server:   'devbox run dev' -> http://localhost:${DEV_PORT:-8000}"
echo "  Fixtures: 'devbox run -- make load_fixtures'"
