name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    services:
      postgres:
        image: postgres:9.5
        env:
          POSTGRES_DB: queremossaber
          POSTGRES_PASSWORD: queremossaber
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip poetry
        make install

    - name: Copy environment file
      run: cp .env.example .env

    - name: Test
      run: make test

    - name: Run migrations
      run: make migrate

    - name: Load fixtures
      run: make load_fixtures
