"""
Django settings for web project.

Generated by 'django-admin startproject' using Django 2.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""
import os
import base64
import json
import environ
from google.oauth2 import service_account
import django_heroku


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

DEFAULT_ENV_PATH = os.path.join(BASE_DIR, '.env')
env = environ.Env(
    DEBUG=(bool, False),
    ENV_PATH=(str, DEFAULT_ENV_PATH),
    ENABLE_GCLOUD=(bool, False),
)
env.read_env(env.str('ENV_PATH'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

ALLOWED_HOSTS = []

INTERNAL_IPS = [
    '127.0.0.1',
]

# Application definition

INSTALLED_APPS = [
    'web.foi_requests',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'livesync',
    'django.contrib.staticfiles',
    'widget_tweaks',
    'debug_toolbar',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'livesync.core.middleware.DjangoLiveSyncMiddleware',
]

ROOT_URLCONF = 'web.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'web', 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'web.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': env.db(),
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'Brazil/East'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'web', 'static'),
]

# Uploaded files variables. Will only be used if ENABLE_GCLOUD is False.
MEDIA_URL = '/upload/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Setup uploads to Google Cloud
def _get_google_credentials():
    if 'GOOGLE_APPLICATION_CREDENTIALS' in os.environ:
        return

    credentials_b64 = env('GS_APPLICATION_CREDENTIALS_BASE64')
    credentials = json.loads(base64.b64decode(credentials_b64))
    return service_account.Credentials.from_service_account_info(credentials)


ENABLE_GCLOUD = env('ENABLE_GCLOUD')
if ENABLE_GCLOUD:
    gcloud_env_keys = set([
        'GOOGLE_APPLICATION_CREDENTIALS',
        'GS_APPLICATION_CREDENTIALS_BASE64',
    ])
    assert gcloud_env_keys.intersection(set(os.environ.keys())), \
        'To enable GCloud storage you must set one of {}'.format(gcloud_env_keys)

    DEFAULT_FILE_STORAGE = 'storages.backends.gcloud.GoogleCloudStorage'
    GS_DEFAULT_ACL = 'publicRead'
    GS_BUCKET_NAME = env('GS_BUCKET_NAME')
    GS_FILE_OVERWRITE = False
    GS_LOCATION = 'uploads'
    GS_CACHE_CONTROL = 'public, max-age=31556926'
    GS_CREDENTIALS = _get_google_credentials()

# Configure Heroku
django_heroku.settings(locals())

# FIXME: This is a workaround because WhiteNoise's files storage raises error 500.
# http://whitenoise.evans.io/en/stable/django.html#troubleshooting-the-whitenoise-storage-backend
STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'
